spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 讓 Hibernate 看著你的 Java Entity（Doctor.java 等）自動在 PostgreSQL 建立正確的表
spring.jpa.hibernate.ddl-auto=update

# 把 SQL 初始化完全關閉，不跟它死磕了
spring.sql.init.mode=never