spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.data-locations=classpath:data-prod.sql

spring.jpa.hibernate.ddl-auto=none

# 強力通行證：強迫 Spring Boot 不管甚麼庫都必須執行 SQL 初始化 ⬇️
spring.sql.init.mode=always
spring.sql.init.username=${spring.datasource.username}
spring.sql.init.password=${spring.datasource.password}