package tw.edu.fju.miniclinic.model;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

@Entity
@Table(name = "patients")
public class Patient {

    @Id
    // Removed @GeneratedValue as String IDs are typically not auto-generated by the database
    private String id; // Changed from Integer to String for custom IDs like TEST00001

    private String name;

    // Constructors
    public Patient() {
    }

    public Patient(String id, String name) {
        this.id = id;
        this.name = name;
    }

    // Getters and Setters
    public String getId() {
        return id;
    }

    public void setId(String id) { // Changed parameter type to String
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}